### ISSUE TITLE
Image Elements

### ISSUE THREAD

**Issue by thebobfather2** [thebobfather2/horiseonmarketing#3]
# Image Elements
## WHEN I view the image elements
THEN I find accessible alt attributes

**Comment by supsa-ak** [comment]
Just explain me this issue. I can solve this.

**Comment by thebobfather2** [comment]
I just need to add alt="description of image for SEO here" to each image after src=""!

**Comment by supsa-ak** [comment]
Ok, I will do this for every image. Assign this issue to me.

**Comment by thebobfather2** [comment]
I actually completed this one, but thank you for the offer Sarthak!
